#!/usr/bin/env node
'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const site=path.join(__dirname,'..','vercel-site');
const index=fs.readFileSync(path.join(site,'index.html'),'utf8');
const success=fs.readFileSync(path.join(site,'success.html'),'utf8');
let passed=0;function test(value,name){assert(value,name);passed++;console.log('  ✓ '+name);}
test(index.includes('id="annualPrice">690<'),'annual price 690 ₽ is rendered without JavaScript');
test(index.includes('id="lifetimePrice">1 790<'),'lifetime price 1 790 ₽ is rendered without JavaScript');
test(index.includes('prices={annual:690,lifetime:1790}'),'client fallback prices match checkout');
test(index.includes("fetch('/api/prices')"),'checkout loads canonical API prices');
test(index.includes("plan:selectedPlan"),'selected plan is sent to payment API');
test(index.includes('двух фигур')&&index.includes('сдвиги')&&index.includes('элементы на пересечениях'),'landing page describes requested pattern modes');
test(index.includes('/terms.html')&&index.includes('/privacy.html'),'legal links are present');
test(index.includes('class="footLogo"')&&index.includes('viewBox="0 0 140 52"')&&index.includes('footRow')&&index.includes('footNote'),'TraceBase-style footer with the LEDNIQUE vector logo is embedded');
test(index.includes('t.me/lednique')&&index.includes('lednique@gmail.com')&&index.includes('ИНН 160101292015'),'footer repeats the TraceBase contact and legal rows');
test(index.includes('id="bgPattern"')&&index.includes('bgLayer')&&index.includes('buildLayer'),'animated pattern background replaces the static demo square');
test(index.includes('HOLD=4000')&&index.includes('cycleTimer=setTimeout(cycle,HOLD+WAVE+GAP)')&&index.includes('transition:background-color 2s linear'),'pattern holds for 4 s between morphs; the background color crossfades');
test(index.includes("document.addEventListener('visibilitychange'")&&index.includes('if(document.hidden)clearTimers();')&&index.includes('else restart();')&&index.includes("window.addEventListener('pageshow'"),'hiding the tab pauses all timers; returning restarts cleanly with no frozen or overlapping layers');
test(index.includes('Watchdog')&&index.includes("!visible.childElementCount||!visible.classList.contains('on')")&&index.includes('!reduced&&!cycleTimer'),'a watchdog guarantees a full pattern is visible on every pass and timers never die');
test(index.includes('Math.max(24,Math.round(cell*')&&index.includes('Math.max(16,Math.round(cell*0.2))')&&index.includes('size1:rand(.46,.88)'),'figure sizes are clamped above zero so the pattern never disappears');
test(index.includes('function prepareNext()')&&index.includes('if(!pending)prepareNext()')&&index.includes('prepareNext();},WAVE+GAP+900'),'the next pattern is randomized and built during the hold, before the morph starts');
test(index.includes('rot1:pick(')&&index.includes('(alt?pat.rot2:pat.rot1)'),'per-object static rotations vary between patterns like the plugin sliders');
test(index.includes('distance(rgb,prevRgb)<0.3'),'random background colors differ by at least 30% between cycles');
test(!index.includes('skinShadow')&&!index.includes('drop-shadow(0 3px 5px')&&index.includes("fill=\"'+color+'\">'+sh.body"),'figures render as plain unfiltered vectors so nothing rasterizes them at reduced resolution');
test(index.includes('transform:scale(.14); opacity:0')&&index.includes('.bgLayer.on .bgShape { transform:scale(1); opacity:1')&&!index.includes('transform:scale(0)')&&!index.includes('rotate(calc(var(--rot'),'morph is scale-only and never uses zero scale: hidden figures keep a small scale with opacity 0');
test(index.includes('setDelays(oldLayer,0)')&&index.includes('setDelays(layer,GAP)')&&index.includes("(r+c)*stepMs"),'the whole pattern morphs as one left-to-right diagonal wave, new figure right after the old');
test(index.includes('cubic-bezier(.26,1.36,.5,1)')&&index.includes('cubic-bezier(.55,.06,.68,.19)'),'figures grow with a gentle back-out and shrink smoothly');
test(index.includes("'grid','grid','checker','checker2','rotate'")&&index.includes('cell*pat.shiftX')&&index.includes('cell*pat.shiftY'),'background replays plugin modes with horizontal and vertical column offsets');
test(index.includes('size1:rand(')&&index.includes('size2:rand(')&&index.includes('alt?pat.size2:pat.size1'),'different figure sizes are shown per object like the plugin sliders');
test(index.includes("decor=Math.random()<0.06?{emoji:pick(EMOJI)}")&&index.includes("shiftX===0&&shiftY===0"),'emoji appears only as the plugin allows: an intersection symbol when offsets are 0');
test(index.includes("fig1=Math.random()<0.03?{emoji:pick(EMOJI)}")&&index.includes("Math.random()<0.06?{emoji:pick(EMOJI)}"),'emojis stay possible but appear rarely (3% figure, 6% intersection)');
test((index.match(/backdrop-filter:blur\(16px\)/g)||[]).length>=7,'translucent blocks use a plain 16px gaussian backdrop blur');
test(!index.includes('will-change'),'background shapes are not layer-promoted, so vectors re-rasterize sharp at full scale');
test(index.includes('.bgLayer.on.settled .bgShape { transform:none; transition:none; }')&&index.includes('settleAfter(newLayer,WAVE+GAP+700)')&&index.includes('settleAfter(layers[0],WAVE+700)'),'settled layers drop transforms so the resting pattern repaints at native resolution');
test(!index.includes('renderFrost')&&!index.includes('--frost'),'the canvas frost snapshot is removed: blur always matches the live pattern with no lag');
test(index.includes('logo:{vb:')&&index.includes('M147.743 0L148.123'),'the provided Patternique logo participates in the background shapes');
test(index.includes('class="hero"')&&index.includes('.hero { margin-bottom:20px; background:linear-gradient(90deg, rgba(222,221,116,.16)')&&index.includes('class="heroTop"')&&index.includes('.featureBar { display:grid; grid-template-columns:repeat(3,1fr)')&&!index.includes('.featureBar { display:flex'),'title, lead, and horizontal features live in one accent-colored block without a separate feature backdrop');
test(index.includes('--card-inset:0px 3px 2px rgba(255,255,255,0.5) inset')&&index.includes('--pill-shadow:0px 3px 6px rgba(0,0,0,0.2)')&&index.includes('--ease-out-back:cubic-bezier(0.01, 1.43, 0.46, 1.85)'),'TraceBase card, pill, and easing styles are reused in the theme color');
test(index.includes('viewBox="0 0 270 154"')&&index.includes('fill="white"'),'the header logo next to Patternique uses the provided mark');
test(index.includes('.head { display:flex; align-items:center; gap:14px; margin-bottom:30px; }'),'all blocks start 30px below the Patternique header');
test(index.includes('.selected .price small, .selected .planDesc { color:var(--accent-hi); }'),'in the selected plan the currency and the text under the price share one readable color');
test(index.includes('rgba(5,7,8,0) 400px, rgba(5,7,8,.55) 600px')&&index.includes('.bgDim { position:absolute'),'background dimming is transparent for 400px, ramps over 200px, and scrolls with the page');
test(!index.includes('class="eyebrow"')&&!index.includes('class="heroPrice"'),'the eyebrow badge and under-title prices are removed');
test(index.includes('.plan.selected { background:linear-gradient(90deg, rgba(222,221,116,.16)')&&index.includes('--tint-dark:rgba(20,20,20,.55)')&&index.includes('.plan { border:none; border-radius:36px; padding:16px 18px; cursor:pointer; background:var(--tint-dark)'),'the selected plan is the colored card; unselected plans use the shared dark tint');
test(index.includes('border-radius:10000px; background:var(--tint-dark); backdrop-filter:blur(16px)')&&index.includes('.pay:disabled { background:var(--tint-dark)'),'email, promo, and the disabled pay button share the inactive plan color');
test(index.includes('input[type="email"]:not(:placeholder-shown)')&&index.includes('rgba(222,221,116,.45)'),'filled fields take the same active yellow treatment');
test(success.includes("fetch('/api/get-key?'+query)"),'success page retrieves paid license key');
test(index.includes('--accent:#DEDD74')&&index.includes('rgba(222,221,116'),'purchase site uses the #DEDD74 theme');
['en','ru','it','pt','fr','zh','ja'].forEach((code)=>test(index.includes('"'+code+'":{'),code+' purchase-site localization exists'));
test(index.includes('id="langMenu"')&&index.includes('buildLangMenu'),'seven-language dropdown is rendered');
['terms.html','privacy.html','manage.html','404.html'].forEach((name)=>test(fs.existsSync(path.join(site,name)),name+' exists'));
const manage=fs.readFileSync(path.join(site,'manage.html'),'utf8');
test(manage.includes('class="card hidden" id="login"')&&manage.includes('id="app"')&&manage.includes('wrap-inner hidden'),'manage panel stays hidden until the password check succeeds');
test(manage.includes("localStorage.getItem('pq_admin_pass')")&&manage.includes("if (d.ok) showApp();"),'saved admin session is re-verified against the API before the panel opens');
test(manage.includes("fetch('/api/admin-keys'")&&manage.includes("'X-Admin-Pass': pass"),'keys are managed through the authenticated admin API');
test(manage.includes("fetch('/api/coupons'")&&manage.includes('refreshCoupons'),'promo codes have their own management section like TraceBase');
test(manage.includes('id="addPlan"')&&manage.includes('id="addDays"')&&manage.includes('id="addEmail"'),'key creation offers plan, validity days, and email like TraceBase');
test(manage.includes('id="cpCode"')&&manage.includes('id="cpPercent"'),'promo creation offers code and discount percent');
test(manage.includes('id="stats"')&&manage.includes('всего ключей'),'stats cards summarize total, active, and activated keys');
test(manage.includes('editRow')&&manage.includes('reset_activation'),'inline key editing and activation reset are available');
test(manage.includes('doLogout')&&manage.includes("localStorage.removeItem('pq_admin_pass')"),'logout clears the stored admin session');
test(manage.includes('--accent:#DEDD74')&&manage.includes('Montserrat'),'manage panel uses the Patternique theme');
console.log('\nSite: '+passed+' checks passed.');
