#!/usr/bin/env node
'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const site=path.join(__dirname,'..','vercel-site');
const index=fs.readFileSync(path.join(site,'index.html'),'utf8');
const success=fs.readFileSync(path.join(site,'success.html'),'utf8');
let passed=0;function test(value,name){assert(value,name);passed++;console.log('  ✓ '+name);}
test(index.includes('id="annualPrice">690<'),'annual price 690 ₽ is rendered without JavaScript');
test(index.includes('id="lifetimePrice">1 790<'),'lifetime price 1 790 ₽ is rendered without JavaScript');
test(index.includes('prices={annual:690,lifetime:1790}'),'client fallback prices match checkout');
test(index.includes("fetch('/api/prices')"),'checkout loads canonical API prices');
test(index.includes("plan:selectedPlan"),'selected plan is sent to payment API');
test(index.includes('двух фигур')&&index.includes('сдвиги')&&index.includes('элементы на пересечениях'),'landing page describes requested pattern modes');
test(index.includes('/terms.html')&&index.includes('/privacy.html'),'legal links are present');
test(index.includes('data:image/png;base64,')&&!index.includes('__LED_FOOTER_B64__'),'footer logo is embedded');
test(success.includes("fetch('/api/get-key?'+query)"),'success page retrieves paid license key');
test(index.includes('--accent:#DEDD74')&&index.includes('rgba(222,221,116'),'purchase site uses the #DEDD74 theme');
['en','ru','it','pt','fr','zh','ja'].forEach((code)=>test(index.includes('"'+code+'":{'),code+' purchase-site localization exists'));
test(index.includes('id="langMenu"')&&index.includes('buildLangMenu'),'seven-language dropdown is rendered');
['terms.html','privacy.html','manage.html','404.html'].forEach((name)=>test(fs.existsSync(path.join(site,name)),name+' exists'));
const manage=fs.readFileSync(path.join(site,'manage.html'),'utf8');
test(manage.includes('class="card hidden" id="login"')&&manage.includes('id="app"')&&manage.includes('wrap-inner hidden'),'manage panel stays hidden until the password check succeeds');
test(manage.includes("localStorage.getItem('pq_admin_pass')")&&manage.includes("if (d.ok) showApp();"),'saved admin session is re-verified against the API before the panel opens');
test(manage.includes("fetch('/api/admin-keys'")&&manage.includes("'X-Admin-Pass': pass"),'keys are managed through the authenticated admin API');
test(manage.includes("fetch('/api/coupons'")&&manage.includes('refreshCoupons'),'promo codes have their own management section like TraceBase');
test(manage.includes('id="addPlan"')&&manage.includes('id="addDays"')&&manage.includes('id="addEmail"'),'key creation offers plan, validity days, and email like TraceBase');
test(manage.includes('id="cpCode"')&&manage.includes('id="cpPercent"'),'promo creation offers code and discount percent');
test(manage.includes('id="stats"')&&manage.includes('всего ключей'),'stats cards summarize total, active, and activated keys');
test(manage.includes('editRow')&&manage.includes('reset_activation'),'inline key editing and activation reset are available');
test(manage.includes('doLogout')&&manage.includes("localStorage.removeItem('pq_admin_pass')"),'logout clears the stored admin session');
test(manage.includes('--accent:#DEDD74')&&manage.includes('Montserrat'),'manage panel uses the Patternique theme');
console.log('\nSite: '+passed+' checks passed.');
