#!/usr/bin/env node
'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const site=path.join(__dirname,'..','vercel-site');
const index=fs.readFileSync(path.join(site,'index.html'),'utf8');
const success=fs.readFileSync(path.join(site,'success.html'),'utf8');
let passed=0;function test(value,name){assert(value,name);passed++;console.log('  ✓ '+name);}
test(index.includes('id="annualPrice">690<'),'annual price 690 ₽ is rendered without JavaScript');
test(index.includes('id="lifetimePrice">1 790<'),'lifetime price 1 790 ₽ is rendered without JavaScript');
test(index.includes('prices={annual:690,lifetime:1790}'),'client fallback prices match checkout');
test(index.includes("fetch('/api/prices')"),'checkout loads canonical API prices');
test(index.includes("plan:selectedPlan"),'selected plan is sent to payment API');
test(index.includes('двух фигур')&&index.includes('сдвиги')&&index.includes('элементы на пересечениях'),'landing page describes requested pattern modes');
test(index.includes('/terms.html')&&index.includes('/privacy.html'),'legal links are present');
test(index.includes('class="footLogo"')&&index.includes('viewBox="0 0 140 52"')&&index.includes('footRow')&&index.includes('footNote'),'TraceBase-style footer with the LEDNIQUE vector logo is embedded');
test(index.includes('t.me/lednique')&&index.includes('lednique@gmail.com')&&index.includes('ИНН 160101292015'),'footer repeats the TraceBase contact and legal rows');
test(index.includes('id="bgPattern"')&&index.includes('bgLayer')&&index.includes('buildLayer'),'animated pattern background replaces the static demo square');
test(index.includes('setInterval(cycle,7000)')&&index.includes('transition:opacity 2s linear'),'background appears for 2 s, holds 5 s, and crossfades into the next pattern');
test(index.includes('distance(rgb,prevRgb)<0.3'),'random background colors differ by at least 30% between cycles');
test(index.includes('filter="url(#skinShadow)"')&&index.includes('skinShadow')&&index.includes('feBlend mode="overlay"'),'figures use the provided leather dddiii shadow recipe without its color');
test(index.includes("(r+c)*delayStep")&&index.includes('var(--ease-out-back)')&&index.includes('.bgLayer.on .bgShape'),'shapes fly in as a diagonal domino with a TraceBase-style back-out bounce');
test(index.includes("'grid','checker','checker2','rotate','shift'")&&index.includes('INTER'),'background randomly shows different pattern modes including intersections');
test(index.includes('bgEmoji')&&index.includes('EMOJI='),'emojis occasionally appear in the background pattern');
test(index.includes('logo:{vb:')&&index.includes('M147.743 0L148.123'),'the provided Patternique logo participates in the background shapes');
test(index.includes('class="featureBar"')&&index.includes('featureCell'),'two shapes, rhythm, and intersection blocks are merged into one horizontal figure');
test(index.includes('--card-inset:0px 3px 2px rgba(255,255,255,0.5) inset')&&index.includes('--pill-shadow:0px 3px 6px rgba(0,0,0,0.2)')&&index.includes('--ease-out-back:cubic-bezier(0.01, 1.43, 0.46, 1.85)'),'TraceBase card, pill, and easing styles are reused in the theme color');
test(index.includes('viewBox="0 0 270 154"')&&index.includes('fill="white"'),'the header logo next to Patternique uses the provided mark');
test(index.includes('.hero { padding:14px 0 0')&&index.includes('gap:20px')&&index.includes('margin-bottom:20px'),'title and feature bar are raised 40px with 20px block spacing');
test(success.includes("fetch('/api/get-key?'+query)"),'success page retrieves paid license key');
test(index.includes('--accent:#DEDD74')&&index.includes('rgba(222,221,116'),'purchase site uses the #DEDD74 theme');
['en','ru','it','pt','fr','zh','ja'].forEach((code)=>test(index.includes('"'+code+'":{'),code+' purchase-site localization exists'));
test(index.includes('id="langMenu"')&&index.includes('buildLangMenu'),'seven-language dropdown is rendered');
['terms.html','privacy.html','manage.html','404.html'].forEach((name)=>test(fs.existsSync(path.join(site,name)),name+' exists'));
const manage=fs.readFileSync(path.join(site,'manage.html'),'utf8');
test(manage.includes('class="card hidden" id="login"')&&manage.includes('id="app"')&&manage.includes('wrap-inner hidden'),'manage panel stays hidden until the password check succeeds');
test(manage.includes("localStorage.getItem('pq_admin_pass')")&&manage.includes("if (d.ok) showApp();"),'saved admin session is re-verified against the API before the panel opens');
test(manage.includes("fetch('/api/admin-keys'")&&manage.includes("'X-Admin-Pass': pass"),'keys are managed through the authenticated admin API');
test(manage.includes("fetch('/api/coupons'")&&manage.includes('refreshCoupons'),'promo codes have their own management section like TraceBase');
test(manage.includes('id="addPlan"')&&manage.includes('id="addDays"')&&manage.includes('id="addEmail"'),'key creation offers plan, validity days, and email like TraceBase');
test(manage.includes('id="cpCode"')&&manage.includes('id="cpPercent"'),'promo creation offers code and discount percent');
test(manage.includes('id="stats"')&&manage.includes('всего ключей'),'stats cards summarize total, active, and activated keys');
test(manage.includes('editRow')&&manage.includes('reset_activation'),'inline key editing and activation reset are available');
test(manage.includes('doLogout')&&manage.includes("localStorage.removeItem('pq_admin_pass')"),'logout clears the stored admin session');
test(manage.includes('--accent:#DEDD74')&&manage.includes('Montserrat'),'manage panel uses the Patternique theme');
console.log('\nSite: '+passed+' checks passed.');
