#!/usr/bin/env node
'use strict';
const assert=require('assert');const fs=require('fs');const path=require('path');
const source=fs.readFileSync(path.join(__dirname,'..','src','ui-template.html'),'utf8');const built=fs.readFileSync(path.join(__dirname,'..','ui.html'),'utf8');let passed=0;
function test(value,name){assert(value,name);passed++;console.log('  ✓ '+name);}
test(source.includes('.previewDock{position:sticky;top:5px'),'preview is sticky with a 5 px top offset');
test(source.includes("previewProgress=Math.max(0,Math.min(1,window.scrollY/180))")&&!source.includes("classList.toggle('compact'"),'preview geometry follows scroll continuously without snapping');
test(source.includes('.patternBackdrop{position:absolute;z-index:0;left:0;right:0;top:0')&&source.includes('.page{position:relative;z-index:1'),'pattern backdrop spans the plugin width and scrolls behind all interface content');
test(source.includes('fadeStart=backdropAnchorY+256,height=Math.ceil(fadeStart+200)')&&source.includes("makeTile(settings,'#DEDD74',true)"),'transparent theme pattern fades for 200 px below the original preview');
test(source.includes("$('patternBackdropCanvas').style.opacity=String(1-previewProgress)")&&source.includes('backdropAnchorY===null'),'backdrop pattern stays anchored and only fades while the preview transforms');
test(source.includes('.previewDock{position:sticky;top:5px;z-index:35')&&source.includes('.previewDock+.card{position:relative;z-index:16'),'sticky preview stays above repeat-mode cards');
test(source.includes('var display=256+(172-256)*previewProgress')&&source.includes('top:-100px;width:100%;height:356px'),'full preview renders the central tile at 100% scale and 100 px higher');
test(source.includes('.previewDock+.card')&&source.includes('margin-top:-100px'),'settings are raised 100 px over the preview continuation');
test(source.includes("ctx.lineWidth=3")&&source.includes("ctx.strokeStyle='#DEDD74'")&&source.includes('radius=8+(22-8)*previewProgress'),'central tile has a yellow 3 px border and 8 px starting radius');
test(source.includes('for(var row=startRow;row<=endRow;row++)')&&source.includes('ctx.drawImage(ghost,originX+column*256'),'background repeats are transparent theme-colored figures across the full plugin width');
test(source.includes("out.contentEditable='true'")&&source.includes("input.value=value"),'slider values support direct keyboard entry');
test(!source.includes('stopImmediatePropagation')&&!source.includes('thumb/2+3'),'clicking anywhere on a slider is no longer blocked');
test(source.includes('pluginDrop')&&source.includes("source:'patternique'"),'central preview square starts a Figma drag and drop');
test(source.includes('-webkit-appearance:auto;appearance:auto')&&source.includes('colorspace="display-p3"')&&source.includes('input.showPicker()'),'color controls explicitly open the standard platform picker');
test(source.includes('id="size1" type="range" min="10" max="150"')&&source.includes('id="size2" type="range" min="10" max="150"'),'object size can be increased up to 150%');
test(source.includes('item.renderWidth||item.width')&&source.includes('fitted.factor'),'preview scales rendered effects with the same factor used by Figma export');
test(!source.includes('id="cellWidth"')&&!source.includes('id="cellHeight"'),'cell width and height inputs are removed');
test(source.includes('id="halfGrid"')&&source.includes('id="halfHorizontal"')&&source.includes('id="halfVertical"'),'half-size grid has horizontal and vertical checkboxes');
test(source.includes('id="shiftEnabled"')&&!source.includes('id="shiftMode"'),'alternate offset is a single both-directions checkbox');
test(source.includes('checkerInline')&&source.includes('data-checker="1"')&&source.includes('data-checker="2"'),'checker layouts 1 and 2 are embedded in the mode button');
test(source.includes("$('checkerSlot').appendChild($('decorationPanel'))"),'intersection controls move into checker mode settings');
test(source.includes('class="objectGrid"')&&source.includes('objectPanel inactive'),'object settings use two persistent columns');
test(!source.includes('selectionTitle')&&!source.includes('selectionMeta')&&!source.includes('selectionIcon'),'selection labels, dimensions, and icon are removed from preview');
test(source.includes('--accent:#DEDD74')&&built.includes('data:image/png;base64,')&&!built.includes('__TRACEBASE_LOGO_B64__'),'new theme and embedded TraceBase-style logo are built');
['en','ru','it','pt','fr','zh','ja'].forEach((code)=>test(source.includes(code+':{subtitle:'),code+' plugin localization exists'));
console.log('\nPlugin UI: '+passed+' checks passed.');
