#!/usr/bin/env node
'use strict';
const assert=require('assert');const fs=require('fs');const path=require('path');
const source=fs.readFileSync(path.join(__dirname,'..','src','ui-template.html'),'utf8');const built=fs.readFileSync(path.join(__dirname,'..','ui.html'),'utf8');const sliderSvg=fs.readFileSync(path.join(__dirname,'..','src','assets','slider-thumb.svg'),'utf8');let passed=0;
function test(value,name){assert(value,name);passed++;console.log('  ✓ '+name);}
test(source.includes('.previewDock{position:sticky;top:5px'),'preview is sticky with a 5 px top offset');
test(source.includes("previewProgress=Math.max(0,Math.min(1,window.scrollY/180))")&&!source.includes("classList.toggle('compact'"),'preview geometry follows scroll continuously without snapping');
test(source.includes('.baseGradient{position:fixed;z-index:0')&&source.includes('linear-gradient(180deg,var(--grad)'),'original theme gradient is restored behind the plugin');
test(source.includes('.patternBackdrop{position:absolute;z-index:1;left:0;right:0;top:0')&&source.includes('.page{position:relative;z-index:2'),'pattern backdrop spans the plugin width and remains behind all interface content');
test(source.includes('fadeStart=backdropAnchorY+256,height=Math.ceil(fadeStart+200)')&&source.includes("makeTile(settings,'#DEDD74',true)"),'transparent theme pattern fades for 200 px below the original preview');
test(source.includes("$('patternBackdropCanvas').style.opacity=String(0.5*(1-previewProgress))")&&source.includes('backdropAnchorY===null'),'anchored backdrop starts at 50% opacity and only fades while the preview transforms');
test(source.includes('.scrollPreviewGlow')&&source.includes('opacity:var(--preview-progress)'),'a scroll-only gradient appears between the central preview and settings');
test(source.includes('.previewStage')&&source.includes('box-shadow:none')&&source.includes('.previewHint')&&source.includes('background:transparent'),'semi-transparent shrinking wrapper around the center preview is removed');
test(source.includes('.previewDock{position:sticky;top:5px;z-index:35')&&source.includes('.previewDock+.card{position:relative;z-index:16'),'sticky preview stays above repeat-mode cards');
test(source.includes('var display=256+(172-256)*previewProgress')&&source.includes('top:-100px;width:100%;height:356px'),'full preview renders the central tile at 100% scale and 100 px higher');
test(source.includes('.previewDock+.card')&&source.includes('margin-top:-100px'),'settings are raised 100 px over the preview continuation');
test(source.includes("ctx.lineWidth=3")&&source.includes("ctx.strokeStyle='#D9D9D9'")&&source.includes('radius=8+(22-8)*previewProgress'),'central tile has a #D9D9D9 3 px border and 8 px starting radius');
test(source.includes("makeTile(settings,null,false,512)"),'central preview tile renders at 512 × 512 px while the export stays 256 px');
test(source.includes("ctx.fillStyle='#FFFFFF'")&&source.includes('Empty state keeps the same white card'),'empty selection shows a white tile with the same #D9D9D9 border');
test(source.includes('for(var row=startRow;row<=endRow;row++)')&&source.includes('ctx.drawImage(ghost,originX+column*256'),'background repeats are transparent theme-colored figures across the full plugin width');
test(source.includes("out.contentEditable='true'")&&source.includes("input.value=value"),'slider values support direct keyboard entry');
test(!source.includes('stopImmediatePropagation')&&!source.includes('thumb/2+3'),'clicking anywhere on a slider is no longer blocked');
test(source.includes('pluginDrop')&&source.includes("source:'patternique'"),'central preview square starts a Figma drag and drop');
test(source.includes('-webkit-appearance:auto;appearance:auto')&&source.includes('colorspace="display-p3"')&&source.includes('input.showPicker()'),'color controls explicitly open the standard platform picker');
test(source.includes('id="size1" type="range" min="10" max="150"')&&source.includes('id="size2" type="range" min="10" max="150"'),'object size can be increased up to 150%');
test(source.includes('item.renderWidth||item.width')&&source.includes('fitted.factor'),'preview scales rendered effects with the same factor used by Figma export');
test(!source.includes('id="cellWidth"')&&!source.includes('id="cellHeight"'),'cell width and height inputs are removed');
test(source.includes('id="halfGrid"')&&source.includes('id="halfHorizontal"')&&source.includes('id="halfVertical"'),'half-size grid has horizontal and vertical checkboxes');
test(source.includes('id="shiftEnabled"')&&!source.includes('id="shiftMode"'),'alternate offset is a single both-directions checkbox');
test(source.includes('checkerInline')&&source.includes('data-checker="1"')&&source.includes('data-checker="2"'),'checker layouts 1 and 2 are embedded in the mode button');
test(source.includes('id="decorationPanel"')&&!source.includes('checkerSlot')&&source.indexOf('id="decorationPanel"')<source.indexOf('id="columns"'),'intersection element block sits back at the top next to the repeat modes');
test(source.includes("shiftBlocked=s.shiftEnabled&&(s.shiftX!==0||s.shiftY!==0)")&&source.includes("$('decorNotice').classList.toggle('hidden',!shiftBlocked)"),'intersection card is only disabled by an active column offset');
test(source.includes("$('decorationControls').classList.toggle('hidden',shiftBlocked)")&&source.includes('.decorNotice{display:flex;align-items:center;justify-content:center;height:34px'),'offset warning replaces the 34 px figure row without resizing the card');
test(source.includes('id="decorationRotation" type="range" min="-180" max="180" step="5" value="0"'),'intersection element has a rotation slider');
test(source.includes('id="decorDetails"')&&source.indexOf('id="background"')<source.indexOf('id="decorDetails"'),'element color, size, and rotation live in Objects and background after the background color');
test(source.includes("secondActive=two||(state.mode==='checker'&&state.checkerLayout===2)"),'checker layout 2 unlocks the second object panel for recoloring');
test(source.includes('class="objectGrid"')&&source.includes('objectPanel inactive'),'object settings use two persistent columns');
test(!source.includes('selectionTitle')&&!source.includes('selectionMeta')&&!source.includes('selectionIcon'),'selection labels, dimensions, and icon are removed from preview');
test(source.includes('viewBox="0 0 270 154"')&&source.includes('font-size:24px')&&source.includes('font-weight:500'),'provided header figure and black 24 px medium title are used');
test(source.includes('font-style:normal')&&source.includes('data-checker="1"'),'checker layout digits are not italic');
test(source.includes('modeGlider')&&source.includes('transition:left 150ms')&&source.includes('requestAnimationFrame(updateModeGlider)'),'mode selection glider flies between buttons in 150 ms');
test(source.includes('.modeSegment>button:hover .modeText')&&source.includes('transform:scale(1.08)')&&!source.includes('scale(1.08) translateY(-1px)'),'mode text hover animation scales from the center of the label');
test(source.includes('input[type=range]::-webkit-slider-thumb:hover{transform:scale(1.08)}'),'slider thumbs use the same centered hover animation');
test(source.includes('.decorTypes button:not(.active):hover .decorGlyph'),'inactive intersection figures use the same centered hover animation');
test(source.includes('.activateBtn:hover:not(:disabled),.buyBtn:hover:not(:disabled)')&&source.includes('.activateBtn:after,.buyBtn:after'),'license buttons use hover motion and active-mode shadow layers');
test(source.includes('0 3px 6px rgba(0,0,0,.2),2px 0 1px')&&source.includes('inset 0 2px 12px')&&source.includes('inset 0 2px 2px rgba(255,255,255,1)')&&source.includes('mix-blend-mode:lighten'),'buttons use the new dddiii shadow recipe with lighten white highlights');
test(source.includes('width:34px;height:26px')&&source.includes('__SLIDER_THUMB_B64__')&&sliderSvg.includes('width="22" height="14" rx="7"')&&sliderSvg.includes('filter0_dddiii_126_153')&&sliderSvg.includes('mode="lighten"'),'slider thumb embeds the provided dddiii 22 × 14 pill SVG');
test(source.includes('var state={mode:\'grid\',checkerLayout:1,decoration:\'star\'}')&&source.includes('id="shiftEnabled" type="checkbox" checked')&&source.includes('id="shiftX" type="range" min="-100" max="100" value="50"')&&source.includes('id="rotationStep" type="range" min="-180" max="180" step="15" value="-15"')&&source.includes('id="size1" type="range" min="10" max="150" value="70"')&&source.includes('id="size2" type="range" min="10" max="150" value="40"')&&source.includes('id="rotation2" type="range" min="-180" max="180" step="5" value="180"')&&source.includes('id="decorationSize" type="range" min="4" max="100" value="25"'),'all requested first-open defaults are present');
test(!source.includes('id="decorationHost"')&&!source.includes('id="decorationCard"'),'legacy hidden intersection host is removed');
test(source.includes('transition:left 150ms cubic-bezier(.25,1.11,.5,1.21),width 150ms cubic-bezier(.25,1.11,.5,1.21)'),'mode glider easing is softened about 4x at the start and end');
test(source.includes('margin-top:-7.5px'),'slider thumb pill is vertically centered on the track');
test(source.includes('--accent:#DEDD74')&&built.includes('data:image/png;base64,')&&!built.includes('__LEDNIQUE_B64__'),'new theme and footer branding are built');
['en','ru','it','pt','fr','zh','ja'].forEach((code)=>test(source.includes(code+':{subtitle:'),code+' plugin localization exists'));
console.log('\nPlugin UI: '+passed+' checks passed.');
